### ISSUE TITLE
Milestone 1: User Auth

### ISSUE THREAD

**Issue by elliejy** [elliejy/Robinhoody#2]
Robinhoody is now accepting [new signup applications](https://robinhoody.herokuapp.com/#/)!  https://robinhoody.herokuapp.com/#/

**Comment by evhumphrey** [comment]
Looks good! 

## Feedback: 

- [ ] Set margin to 0 for the body (also, you should have a css reset file if you don't already)
- [ ] For things that have hover effects, adding a `transition` to the non-hovered element will have a cool fade effect

### Sign Up form
- [ ] Add `:focus` styling so that when a user clicked on the input, the background color changes to white, and the border changes to the robinhoody green color (also remove the default `outline` with css)
- [ ] Change `:hover` styling to have a white background and grayish border for the inputs
- [ ] Change the color of the `Sign up here` to match the button color (robinhoody green), and remove the underline (check out `text-decoration`)
- [ ] Change the `:hover` color for the "Sign Up" button to be a different shade of blue/green, rather than gray (match the demo button hover color to this)
- [ ] Have a `cursor: pointer` for buttons when hovered
- [ ] Increase height of inputs a bit 
- [ ] Increase font size a tiny bit
- [ ] (Similar styling for Log In Form)
![Screen Shot 2019-07-08 at 3 49 42 PM](https://user-images.githubusercontent.com/6361824/60850530-ab2be580-a1a4-11e9-80a1-8443982ab8a1.png)


### Home Page 
- [ ] Remove underlines from non-hovered links 
- [ ] When "Sign Up" buttons are hovered, add an underline and a box shadow, and have the color be white
- [ ] When "Log In" is hovered, add underline (leave the hover color as is)
- [ ] I'd remove "Commissions disclosure"
- [ ] Make the subtext (below the "Invest Commission-Free") font smaller, and increase the `line-height` a little bit
![Screen Shot 2019-07-08 at 5 25 09 PM](https://user-images.githubusercontent.com/6361824/60850757-97cd4a00-a1a5-11e9-9a5a-9de7ba94696d.png)
